version: "3"
services:
  
  az-server:
    image: server-app 
    command: python -u ./server.py
    ports:
      - 65432:65432
    environment:
      - "constraint:node==localhost"
    deploy:
      replicas: 1
      restart_policy:
        condition: "on-failure"
  agx-scheduler:
    image: scheduler-app
    command: python -u ./scheduler.py
    ports:
      - 59999:59999
    environment:
      - "constraint:node==agx6.nodes.edgelab.network"
    deploy:
      replicas: 1
      restart_policy:
        condition: "on-failure"
  vv-client:
    image: client-app
    command: python -u ./client.py
    depends_on:
      - az-server
      - agx-scheduler
    deploy:
      replicas: 5
      restart_policy:
        condition: "on-failure"
    environment:
      - "contraint:node==172.25.16.67"